sudo: false
language: python
install: python -m pip install tox
script: python -m tox -e py
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      env: TOXENV=py37
    - python: 3.7
      dist: xenial
      env: TOXENV=lint
